# Generated by Django 2.2.16 on 2022-12-12 03:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221210_2205'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Подписка на себя',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='no_self_follow'),
        ),
    ]
